/**********************************************************************
 * BIGMATH INSIGHT CONFIDENTIAL
 *
 * Copyright (C) 2016-2018 BIGMATH CORPORATION, All Rights Reserved.
 *
 * @Author: Simon Zhang on 19 Oct 2018
 * @EMail: simon.zhangsm@hotmail.com
 * @Version: $BIGMATH_SIMD_LIB_VERSION
 *
 * These source codes are subject to the terms and conditions defined
 * in 'LICENSE', which is part of this source code package. Write to
 * LICENSE@BIGMATH.COM for more authorization requirements, or obtain
 * an entire copy of license agreement at http://bigmath.com/license.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * **********************************************************************/
#ifndef SIMD_PREPROCESSOR_TUPLE_EAT_HPP
#define SIMD_PREPROCESSOR_TUPLE_EAT_HPP
#
#include <bigmath/simd/detail/preprocessor/config/config.hpp>
#
#/* SIMD_EAT */
#
#if SIMD_VARIADICS
#define SIMD_EAT(...)
#else
#define SIMD_EAT(x)
#endif
#
#/* SIMD_TUPLE_EAT */
#
#if SIMD_VARIADICS
#define SIMD_TUPLE_EAT(size) SIMD_EAT
#else
#if ~SIMD_CONFIG_FLAGS() & SIMD_CONFIG_MWCC()
#define SIMD_TUPLE_EAT(size) SIMD_TUPLE_EAT_I(size)
#else
#define SIMD_TUPLE_EAT(size) SIMD_TUPLE_EAT_OO((size))
#define SIMD_TUPLE_EAT_OO(par) SIMD_TUPLE_EAT_I##par
#endif
#define SIMD_TUPLE_EAT_I(size) SIMD_TUPLE_EAT_##size
#endif
#
#if ~SIMD_CONFIG_FLAGS() & SIMD_CONFIG_MWCC()
#define SIMD_TUPLE_EAT_N(size) SIMD_TUPLE_EAT_N_I(size)
#else
#define SIMD_TUPLE_EAT_N(size) SIMD_TUPLE_EAT_N_OO((size))
#define SIMD_TUPLE_EAT_N_OO(par) SIMD_TUPLE_EAT_N_I##par
#endif
#define SIMD_TUPLE_EAT_N_I(size) SIMD_TUPLE_EAT_##size
#
#define SIMD_TUPLE_EAT_1(e0)
#define SIMD_TUPLE_EAT_2(e0, e1)
#define SIMD_TUPLE_EAT_3(e0, e1, e2)
#define SIMD_TUPLE_EAT_4(e0, e1, e2, e3)
#define SIMD_TUPLE_EAT_5(e0, e1, e2, e3, e4)
#define SIMD_TUPLE_EAT_6(e0, e1, e2, e3, e4, e5)
#define SIMD_TUPLE_EAT_7(e0, e1, e2, e3, e4, e5, e6)
#define SIMD_TUPLE_EAT_8(e0, e1, e2, e3, e4, e5, e6, e7)
#define SIMD_TUPLE_EAT_9(e0, e1, e2, e3, e4, e5, e6, e7, e8)
#define SIMD_TUPLE_EAT_10(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9)
#define SIMD_TUPLE_EAT_11(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10)
#define SIMD_TUPLE_EAT_12(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11)
#define SIMD_TUPLE_EAT_13(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12)
#define SIMD_TUPLE_EAT_14(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13)
#define SIMD_TUPLE_EAT_15(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14)
#define SIMD_TUPLE_EAT_16(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15)
#define SIMD_TUPLE_EAT_17(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16)
#define SIMD_TUPLE_EAT_18(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17)
#define SIMD_TUPLE_EAT_19(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18)
#define SIMD_TUPLE_EAT_20(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19)
#define SIMD_TUPLE_EAT_21(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20)
#define SIMD_TUPLE_EAT_22( \
    e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21)
#define SIMD_TUPLE_EAT_23( \
    e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22)
#define SIMD_TUPLE_EAT_24( \
    e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23)
#define SIMD_TUPLE_EAT_25( \
    e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24)
#define SIMD_TUPLE_EAT_26(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25)
#define SIMD_TUPLE_EAT_27(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26)
#define SIMD_TUPLE_EAT_28(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27)
#define SIMD_TUPLE_EAT_29(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28)
#define SIMD_TUPLE_EAT_30(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29)
#define SIMD_TUPLE_EAT_31(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30)
#define SIMD_TUPLE_EAT_32(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31)
#define SIMD_TUPLE_EAT_33(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32)
#define SIMD_TUPLE_EAT_34(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33)
#define SIMD_TUPLE_EAT_35(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34)
#define SIMD_TUPLE_EAT_36(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35)
#define SIMD_TUPLE_EAT_37(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36)
#define SIMD_TUPLE_EAT_38(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37)
#define SIMD_TUPLE_EAT_39(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38)
#define SIMD_TUPLE_EAT_40(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39)
#define SIMD_TUPLE_EAT_41(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40)
#define SIMD_TUPLE_EAT_42(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41)
#define SIMD_TUPLE_EAT_43(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42)
#define SIMD_TUPLE_EAT_44(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43)
#define SIMD_TUPLE_EAT_45(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44)
#define SIMD_TUPLE_EAT_46(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45)
#define SIMD_TUPLE_EAT_47(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46)
#define SIMD_TUPLE_EAT_48(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47)
#define SIMD_TUPLE_EAT_49(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48)
#define SIMD_TUPLE_EAT_50(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49)
#define SIMD_TUPLE_EAT_51(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50)
#define SIMD_TUPLE_EAT_52(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51)
#define SIMD_TUPLE_EAT_53(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52)
#define SIMD_TUPLE_EAT_54(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53)
#define SIMD_TUPLE_EAT_55(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54)
#define SIMD_TUPLE_EAT_56(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55)
#define SIMD_TUPLE_EAT_57(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56)
#define SIMD_TUPLE_EAT_58(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57)
#define SIMD_TUPLE_EAT_59(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58)
#define SIMD_TUPLE_EAT_60(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58, \
                          e59)
#define SIMD_TUPLE_EAT_61(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58, \
                          e59, \
                          e60)
#define SIMD_TUPLE_EAT_62(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58, \
                          e59, \
                          e60, \
                          e61)
#define SIMD_TUPLE_EAT_63(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58, \
                          e59, \
                          e60, \
                          e61, \
                          e62)
#define SIMD_TUPLE_EAT_64(e0,  \
                          e1,  \
                          e2,  \
                          e3,  \
                          e4,  \
                          e5,  \
                          e6,  \
                          e7,  \
                          e8,  \
                          e9,  \
                          e10, \
                          e11, \
                          e12, \
                          e13, \
                          e14, \
                          e15, \
                          e16, \
                          e17, \
                          e18, \
                          e19, \
                          e20, \
                          e21, \
                          e22, \
                          e23, \
                          e24, \
                          e25, \
                          e26, \
                          e27, \
                          e28, \
                          e29, \
                          e30, \
                          e31, \
                          e32, \
                          e33, \
                          e34, \
                          e35, \
                          e36, \
                          e37, \
                          e38, \
                          e39, \
                          e40, \
                          e41, \
                          e42, \
                          e43, \
                          e44, \
                          e45, \
                          e46, \
                          e47, \
                          e48, \
                          e49, \
                          e50, \
                          e51, \
                          e52, \
                          e53, \
                          e54, \
                          e55, \
                          e56, \
                          e57, \
                          e58, \
                          e59, \
                          e60, \
                          e61, \
                          e62, \
                          e63)
#
#endif
