/**********************************************************************
 * BIGMATH INSIGHT CONFIDENTIAL
 *
 * Copyright (C) 2016-2018 BIGMATH CORPORATION, All Rights Reserved.
 *
 * @Author: Simon Zhang on 19 Oct 2018
 * @EMail: simon.zhangsm@hotmail.com
 * @Version: $SIMD_LIB_VERSION
 *
 * These source codes are subject to the terms and conditions defined
 * in 'LICENSE', which is part of this source code package. Write to
 * LICENSE@BIGMATH.COM for more authorization requirements, or obtain
 * an entire copy of license agreement at http://bigmath.com/license.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * **********************************************************************/

#ifndef SIMD_DETAIL_INSN_ID_H
#define SIMD_DETAIL_INSN_ID_H

// Instruction set ids used when constructing architecture id. The architecture
// id is then used to define SIMD_ARCH_NAMESPACE
#define SIMD_INSN_ID_NULL _null
#define SIMD_INSN_ID_SSE2 _sse2
#define SIMD_INSN_ID_SSE3 _sse3
#define SIMD_INSN_ID_SSSE3 _ssse3
#define SIMD_INSN_ID_SSE4_1 _sse4p1
#define SIMD_INSN_ID_SSE4_2 _sse4p2
#define SIMD_INSN_ID_SSE4A _sse4a
#define SIMD_INSN_ID_POPCNT_INSN _popcnt
#define SIMD_INSN_ID_AVX _avx
#define SIMD_INSN_ID_AVX2 _avx2
#define SIMD_INSN_ID_FMA3 _fma3
#define SIMD_INSN_ID_FMA4 _fma4
#define SIMD_INSN_ID_XOP _xop
#define SIMD_INSN_ID_AVX512F _avx512f
#define SIMD_INSN_ID_AVX512BW _avx512bw
#define SIMD_INSN_ID_AVX512DQ _avx512dq
#define SIMD_INSN_ID_AVX512VL _avx512vl
#define SIMD_INSN_ID_NEON _neon
#define SIMD_INSN_ID_NEON_FLT_SP _neonfltsp
#define SIMD_INSN_ID_ALTIVEC _altivec
#define SIMD_INSN_ID_VSX_206 _vsx_206
#define SIMD_INSN_ID_VSX_207 _vsx_207
#define SIMD_INSN_ID_MSA _msa

// Arbitrary masks used to simplify architecture processing
// (used in preprocess_single_arch.h)
#define SIMD_INSN_MASK_NULL 0x00000001
#define SIMD_INSN_MASK_SSE2 0x00000002
#define SIMD_INSN_MASK_SSE3 0x00000004
#define SIMD_INSN_MASK_SSSE3 0x00000008
#define SIMD_INSN_MASK_SSE4_1 0x00000010
#define SIMD_INSN_MASK_SSE4_2 0x00000020
#define SIMD_INSN_MASK_SSE4A 0x00000040
#define SIMD_INSN_MASK_POPCNT_INSN 0x00000080
#define SIMD_INSN_MASK_AVX 0x00000100
#define SIMD_INSN_MASK_AVX2 0x00000200
#define SIMD_INSN_MASK_FMA3 0x00000400
#define SIMD_INSN_MASK_FMA4 0x00000800
#define SIMD_INSN_MASK_XOP 0x00001000
#define SIMD_INSN_MASK_AVX512F 0x00002000
#define SIMD_INSN_MASK_AVX512BW 0x00004000
#define SIMD_INSN_MASK_AVX512DQ 0x00008000
#define SIMD_INSN_MASK_AVX512VL 0x00010000
#define SIMD_INSN_MASK_NEON 0x00020000
#define SIMD_INSN_MASK_NEON_FLT_SP 0x00040000
#define SIMD_INSN_MASK_ALTIVEC 0x00080000
#define SIMD_INSN_MASK_VSX_206 0x00100000
#define SIMD_INSN_MASK_VSX_207 0x00200000
#define SIMD_INSN_MASK_MSA 0x00400000

#define SIMD_PREFIX_SIMD_ARCH_X86_NULL SIMD_INSN_MASK_NULL
#define SIMD_PREFIX_SIMD_ARCH_X86_SSE2 SIMD_INSN_MASK_SSE2
#define SIMD_PREFIX_SIMD_ARCH_X86_SSE3 SIMD_INSN_MASK_SSE3
#define SIMD_PREFIX_SIMD_ARCH_X86_SSSE3 SIMD_INSN_MASK_SSSE3
#define SIMD_PREFIX_SIMD_ARCH_X86_SSE4_1 SIMD_INSN_MASK_SSE4_1
#define SIMD_PREFIX_SIMD_ARCH_X86_SSE4_2 SIMD_INSN_MASK_SSE4_2
#define SIMD_PREFIX_SIMD_ARCH_X86_SSE4A SIMD_INSN_MASK_SSE4A
#define SIMD_PREFIX_SIMD_ARCH_X86_POPCNT_INSN SIMD_INSN_MASK_POPCNT_INSN
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX SIMD_INSN_MASK_AVX
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX2 SIMD_INSN_MASK_AVX2
#define SIMD_PREFIX_SIMD_ARCH_X86_FMA3 SIMD_INSN_MASK_FMA3
#define SIMD_PREFIX_SIMD_ARCH_X86_FMA4 SIMD_INSN_MASK_FMA4
#define SIMD_PREFIX_SIMD_ARCH_X86_XOP SIMD_INSN_MASK_XOP
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX512F SIMD_INSN_MASK_AVX512F
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX512BW SIMD_INSN_MASK_AVX512BW
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX512DQ SIMD_INSN_MASK_AVX512DQ
#define SIMD_PREFIX_SIMD_ARCH_X86_AVX512VL SIMD_INSN_MASK_AVX512VL
#define SIMD_PREFIX_SIMD_ARCH_ARM_NEON SIMD_INSN_MASK_NEON
#define SIMD_PREFIX_SIMD_ARCH_ARM_NEON_FLT_SP SIMD_INSN_MASK_NEON_FLT_SP
#define SIMD_PREFIX_SIMD_ARCH_POWER_ALTIVEC SIMD_INSN_MASK_ALTIVEC
#define SIMD_PREFIX_SIMD_ARCH_POWER_VSX_206 SIMD_INSN_MASK_VSX_206
#define SIMD_PREFIX_SIMD_ARCH_POWER_VSX_207 SIMD_INSN_MASK_VSX_207
#define SIMD_PREFIX_SIMD_ARCH_MIPS_MSA SIMD_INSN_MASK_MSA

#endif
