/**********************************************************************
 * BIGMATH INSIGHT CONFIDENTIAL
 *
 * Copyright (C) 2016-2018 BIGMATH CORPORATION, All Rights Reserved.
 *
 * @Author: Simon Zhang on 19 Oct 2018
 * @EMail: simon.zhangsm@hotmail.com
 * @Version: $BIGMATH_SIMD_LIB_VERSION
 *
 * These source codes are subject to the terms and conditions defined
 * in 'LICENSE', which is part of this source code package. Write to
 * LICENSE@BIGMATH.COM for more authorization requirements, or obtain
 * an entire copy of license agreement at http://bigmath.com/license.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * **********************************************************************/
#ifndef SIMD_PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP
#define SIMD_PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP

#if SIMD_VARIADICS_MSVC

#include <bigmath/simd/detail/preprocessor/facilities/empty.hpp>

#define SIMD_DETAIL_VD_IBP_CAT(a, b) SIMD_DETAIL_VD_IBP_CAT_I(a, b)
#define SIMD_DETAIL_VD_IBP_CAT_I(a, b) SIMD_DETAIL_VD_IBP_CAT_II(a##b)
#define SIMD_DETAIL_VD_IBP_CAT_II(res) res

#define SIMD_DETAIL_IBP_SPLIT(i, ...)                                                                           \
    SIMD_DETAIL_VD_IBP_CAT(SIMD_DETAIL_IBP_PRIMITIVE_CAT(SIMD_DETAIL_IBP_SPLIT_, i)(__VA_ARGS__), SIMD_EMPTY()) \
    /**/

#define SIMD_DETAIL_IBP_IS_VARIADIC_C(...) 1 1

#else

#define SIMD_DETAIL_IBP_SPLIT(i, ...) SIMD_DETAIL_IBP_PRIMITIVE_CAT(SIMD_DETAIL_IBP_SPLIT_, i)(__VA_ARGS__) /**/

#define SIMD_DETAIL_IBP_IS_VARIADIC_C(...) 1

#endif /* SIMD_VARIADICS_MSVC */

#define SIMD_DETAIL_IBP_SPLIT_0(a, ...) a
#define SIMD_DETAIL_IBP_SPLIT_1(a, ...) __VA_ARGS__

#define SIMD_DETAIL_IBP_CAT(a, ...) SIMD_DETAIL_IBP_PRIMITIVE_CAT(a, __VA_ARGS__)
#define SIMD_DETAIL_IBP_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__

#define SIMD_DETAIL_IBP_IS_VARIADIC_R_1 1,
#define SIMD_DETAIL_IBP_IS_VARIADIC_R_SIMD_DETAIL_IBP_IS_VARIADIC_C 0,

#endif /* SIMD_PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP */
